<a href="https://colab.research.google.com/github/Dharaneesh8/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard/blob/main/SQL_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a rapido data with 5 rows and 7 columns using sql

In [3]:
import sqlite3
import pandas as pd

# Connect to an in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# SQL to create the 'rapido' table with 7 columns
create_table_sql = """
CREATE TABLE rapido (
    id INTEGER PRIMARY KEY,
    item_name TEXT,
    quantity INTEGER,
    price REAL,
    category TEXT,
    order_date DATE,
    is_premium BOOLEAN
);
"""
cursor.execute(create_table_sql)

# SQL to insert 5 rows of data into the 'rapido' table
insert_data_sql = """
INSERT INTO rapido (id, item_name, quantity, price, category, order_date, is_premium) VALUES
(1, 'Laptop', 1, 1200.50, 'Electronics', '2023-10-26', TRUE),
(2, 'Mouse', 2, 25.00, 'Electronics', '2023-10-26', FALSE),
(3, 'Keyboard', 1, 75.99, 'Electronics', '2023-10-27', TRUE),
(4, 'Monitor', 1, 300.00, 'Peripherals', '2023-10-27', FALSE),
(5, 'Webcam', 3, 50.25, 'Peripherals', '2023-10-28', TRUE);
"""
cursor.execute(insert_data_sql)

# Commit the changes to the database
conn.commit()

print("Table 'rapido' created and populated successfully using pure SQL.")

Table 'rapido' created and populated successfully using pure SQL.

Now, let's display the 'rapido' table using pandas to visualize the SQL-created data.

In [4]:
# Fetch the data from the 'rapido' table into a pandas DataFrame for display
df_rapido_sql = pd.read_sql_query("SELECT * FROM rapido", conn)
display(df_rapido_sql)

# Close the database connection
conn.close()
print("Database connection closed.")

   id item_name  quantity    price     category  order_date  is_premium
0   1    Laptop         1  1200.50  Electronics  2023-10-26           1
1   2     Mouse         2    25.00  Electronics  2023-10-26           0
2   3  Keyboard         1    75.99  Electronics  2023-10-27           1
3   4   Monitor         1   300.00  Peripherals  2023-10-27           0
4   5    Webcam         3    50.25  Peripherals  2023-10-28           1

Database connection closed.

In [7]:
import sqlite3
import pandas as pd

# Re-establish connection to an in-memory SQLite database
# An in-memory database is temporary; its contents are lost when the connection is closed.
# Therefore, we need to recreate the table and re-insert data for subsequent operations.
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Recreate the 'rapido' table with the same structure
create_table_sql = """
CREATE TABLE rapido (
    id INTEGER PRIMARY KEY,
    item_name TEXT,
    quantity INTEGER,
    price REAL,
    category TEXT,
    order_date DATE,
    is_premium BOOLEAN
);
"""
cursor.execute(create_table_sql)

# Re-insert the 5 rows of data into the table
insert_data_sql = """
INSERT INTO rapido (id, item_name, quantity, price, category, order_date, is_premium) VALUES
(1, 'Laptop', 1, 1200.50, 'Electronics', '2023-10-26', TRUE),
(2, 'Mouse', 2, 25.00, 'Electronics', '2023-10-26', FALSE),
(3, 'Keyboard', 1, 75.99, 'Electronics', '2023-10-27', TRUE),
(4, 'Monitor', 1, 300.00, 'Peripherals', '2023-10-27', FALSE),
(5, 'Webcam', 3, 50.25, 'Peripherals', '2023-10-28', TRUE);
"""
cursor.execute(insert_data_sql)

# Commit the changes
conn.commit()

print("Database and table re-established for UNION ALL operation.")

Database and table re-established for UNION ALL operation.

Now, let's perform the `UNION ALL` operation. We'll combine all items with `quantity = 1` and all items with `price > 50` from the `rapido` table. Remember, `UNION ALL` includes duplicates if a row satisfies both conditions.

In [8]:
# SQL query using UNION ALL
union_all_sql = """
SELECT id, item_name, quantity, price
FROM rapido
WHERE quantity = 1

UNION ALL

SELECT id, item_name, quantity, price
FROM rapido
WHERE price > 50;
"""

# Execute the UNION ALL query and load into a pandas DataFrame
df_union_all_again = pd.read_sql_query(union_all_sql, conn)

# Display the result
display(df_union_all_again)

# Close the database connection
conn.close()
print("Database connection closed after UNION ALL operation.")

   id item_name  quantity    price
0   1    Laptop         1  1200.50
1   3  Keyboard         1    75.99
2   4   Monitor         1   300.00
3   1    Laptop         1  1200.50
4   3  Keyboard         1    75.99
5   4   Monitor         1   300.00
6   5    Webcam         3    50.25

Database connection closed after UNION ALL operation.

In [9]:
import sqlite3
import pandas as pd

# Re-establish connection to an in-memory SQLite database
# An in-memory database is temporary; its contents are lost when the connection is closed.
# Therefore, we need to recreate the table and re-insert data for subsequent operations.
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Recreate the 'rapido' table with the same structure
create_table_sql = """
CREATE TABLE rapido (
    id INTEGER PRIMARY KEY,
    item_name TEXT,
    quantity INTEGER,
    price REAL,
    category TEXT,
    order_date DATE,
    is_premium BOOLEAN
);
"""
cursor.execute(create_table_sql)

# Re-insert the 5 rows of data into the table
insert_data_sql = """
INSERT INTO rapido (id, item_name, quantity, price, category, order_date, is_premium) VALUES
(1, 'Laptop', 1, 1200.50, 'Electronics', '2023-10-26', TRUE),
(2, 'Mouse', 2, 25.00, 'Electronics', '2023-10-26', FALSE),
(3, 'Keyboard', 1, 75.99, 'Electronics', '2023-10-27', TRUE),
(4, 'Monitor', 1, 300.00, 'Peripherals', '2023-10-27', FALSE),
(5, 'Webcam', 3, 50.25, 'Peripherals', '2023-10-28', TRUE);
"""
cursor.execute(insert_data_sql)

# Commit the changes
conn.commit()

print("Database and table re-established for JOIN operation.")

Database and table re-established for JOIN operation.

Now, let's perform an `INNER JOIN` of the `rapido` table with itself. We will find pairs of items that belong to the same `category` but are not the same item (using `t1.id != t2.id`).

In [10]:
# SQL query using INNER JOIN (self-join)
join_sql = """
SELECT
    t1.item_name AS item1_name,
    t1.category AS item1_category,
    t2.item_name AS item2_name,
    t2.category AS item2_category
FROM
    rapido AS t1
INNER JOIN
    rapido AS t2 ON t1.category = t2.category AND t1.id != t2.id
ORDER BY
    t1.item_name, t2.item_name;
"""

# Execute the JOIN query and load into a pandas DataFrame
df_inner_join = pd.read_sql_query(join_sql, conn)

# Display the result
display(df_inner_join)

# Close the database connection
conn.close()
print("Database connection closed after INNER JOIN operation.")

  item1_name item1_category item2_name item2_category
0   Keyboard    Electronics     Laptop    Electronics
1   Keyboard    Electronics      Mouse    Electronics
2     Laptop    Electronics   Keyboard    Electronics
3     Laptop    Electronics      Mouse    Electronics
4    Monitor    Peripherals     Webcam    Peripherals
5      Mouse    Electronics   Keyboard    Electronics
6      Mouse    Electronics     Laptop    Electronics
7     Webcam    Peripherals    Monitor    Peripherals

Database connection closed after INNER JOIN operation.

In [11]:
import sqlite3
import pandas as pd

# Re-establish connection to an in-memory SQLite database
# An in-memory database is temporary; its contents are lost when the connection is closed.
# Therefore, we need to recreate the table and re-insert data for subsequent operations.
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Recreate the 'rapido' table with the same structure
create_table_sql = """
CREATE TABLE rapido (
    id INTEGER PRIMARY KEY,
    item_name TEXT,
    quantity INTEGER,
    price REAL,
    category TEXT,
    order_date DATE,
    is_premium BOOLEAN
);
"""
cursor.execute(create_table_sql)

# Re-insert the 5 rows of data into the table
insert_data_sql = """
INSERT INTO rapido (id, item_name, quantity, price, category, order_date, is_premium) VALUES
(1, 'Laptop', 1, 1200.50, 'Electronics', '2023-10-26', TRUE),
(2, 'Mouse', 2, 25.00, 'Electronics', '2023-10-26', FALSE),
(3, 'Keyboard', 1, 75.99, 'Electronics', '2023-10-27', TRUE),
(4, 'Monitor', 1, 300.00, 'Peripherals', '2023-10-27', FALSE),
(5, 'Webcam', 3, 50.25, 'Peripherals', '2023-10-28', TRUE);
"""
cursor.execute(insert_data_sql)

# Commit the changes
conn.commit()

print("Database and table re-established for GROUP BY operation.")

Database and table re-established for GROUP BY operation.

Now, I will perform a SQL `GROUP BY` query to calculate the average `price` for each `category`.

In [12]:
# SQL query using GROUP BY to calculate average price per category
group_by_sql = """
SELECT
    category,
    AVG(price) AS average_price
FROM
    rapido
GROUP BY
    category
ORDER BY
    category;
"""

# Execute the GROUP BY query and load into a pandas DataFrame
df_avg_price_per_category = pd.read_sql_query(group_by_sql, conn)

# Display the result
display(df_avg_price_per_category)

# Close the database connection
conn.close()
print("Database connection closed after GROUP BY operation.")

      category  average_price
0  Electronics        433.830
1  Peripherals        175.125

Database connection closed after GROUP BY operation.